name: Release on Tag

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create release zip
        run: |
          zip export_paper_model.zip __init__.py blender_manifest.toml nesting.py pdf.py svg.py unfold_operator.py unfolder.py

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: true
          prerelease: false
          files: export_paper_model.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
